Add extra_flags attribute to PresetProgram
vinisalazar/BioProv pull request #39
Opened 2020-12-05 17:55 UTC by jvfe

Changes made:
- Add extra_flags attribute to PresetProgram + a test case
- Update CHANGELOG with extra_flags
- Refactor Diamond preset to use extra_flags

2020-12-07 11:36 UTC, vinisalazar requested changes
Good job, LGTM. 

The only detail is removing the `extra_flags` arg from the `diamond` function.

2020-12-07 11:36 UTC, vinisalazar commented on bioprov/programs/programs.py
> +        extra_flags=extra_flags,
I believe that this argument should be removed from the function definition. There is already a `extra_flags=None` default option. As is, it seems to me that it will always require passing `extra_flags` when calling diamond, even if passing `extra_flags=None`.

@jvfe could you please edit it?

2020-12-07 11:50 UTC, vinisalazar commented on bioprov/programs/programs.py
> +        extra_flags=extra_flags,
@jvfe please disregard this comment. This is actually fine.

However, a welcome review would be to add this `extra_flags` parameter to the other Presets,

2020-12-07 12:09 UTC, jvfe commented on bioprov/programs/programs.py
> +        extra_flags=extra_flags,
> @jvfe please disregard this last comment. This is actually fine.
> 
> However, a welcome review would be to add this `extra_flags` parameter to the other Presets,

Done! Thanks

2020-12-15 16:49 UTC, vinisalazar approved these changes
Thanks, will merge.

2020-12-15 17:11 UTC, merged